- src/actions.ts
- src/effects.ts
- src/interfaces.ts
- src/reducers.ts
- src/selectors.ts
- src/services.ts
Right now, to add a query one has to send requests to the API using `service.findOne` or `service.findMany`. Sometimes, one needs to fetch data from the store without sending requests to the API. In typical redux/ngrx, we use selectors to do such thing. However, since we have a "query api" ready to use, we can add queries manually and then the results can be extracted from this query.
This PR is not finished!
> WIP: Add queries manually

- karma.conf.js
- package.json
- spec/reducers.spec.ts
- src/interfaces.ts
- src/reducers.ts
- src/utils.ts
Previously the store operations status (isCreating, isUpdating ...)
were booleans. This isn't useful to know for example how many update
operations are being carried out. Therefore, each status was changed to
a number so `isCreating --> 2` means 2 creation operations are being
carried out.
> Change operations status from bool to number

- spec/reducers.spec.ts
- spec/selectors.spec.ts
- spec/test_utils.ts
- spec/utils.spec.ts
- src/interfaces.ts
- src/selectors.ts
- src/utils.ts
Example:
```ts
query = {
type: 'Article',
params: {
filtering: [{path: 'author.lastName', value: 'Smith', type: 'iexact'}]
}
}
service.findMany(query, false);
```
More to come:
> Client side filtering

- package.json
- spec/actions.spec.ts
- spec/reducers.spec.ts
- src/actions.ts
- src/api.ts
- src/effects.ts
- src/interfaces.ts
- src/module.ts
- src/pipes.ts
- src/reducers.ts
- src/selectors.ts
- src/services.ts
- src/utils.ts
- webpack.config.js
- webpack.prod.config.js
Previously, service methods used the "commit" method where they either
add a resource or update it or mark it for deletion. Afterwards a commit
action processes all these. This is useful in many situations. However,
sometimes it is required to perform a patch/post/delete immediately
without using commit.
This PR adds this possibility, for example, to patch a resource and send
the request to the server immediately we use:
```ts
this.service.patch(resource, true)
```
The optional boolean when set to `true` will send `API_DELETE_INIT` or
`API_UPDATE_INIT` or `API_CREATE_INIT` actions.
> Allow service methods to init read/patch/delete

- package.json
- spec/reducers.spec.ts
- src/reducers.ts
- src/utils.ts
There used to be a check in reducers whether queries have a queryId
or not. This has been removed and queries with no queryId will get
a uuid as their id.
> Allow queries with no queryId

- spec/effects.spec.ts
- spec/selectors.spec.ts
- src/selectors.ts
- src/services.ts
- src/utils.ts
To fix "cannot find 'map' of undefined" we catch these 'undefined'
values and deal with them properly.
> Better error handling

- spec/selectors.spec.ts
- src/interfaces.ts
- src/selectors.ts
introduced QueryError and checks when reading a query. 
not yet complete, two tests are broken: currently it is allowed to return undefined. I think the getResultIdentifiers$ should not do that and rather wait for either the response or an error. Any select observable accessing a remote server currently returns first a undefined.
> Support error handling for select services 

- spec/pipes.spec.ts
- spec/services.spec.ts
- spec/utils.spec.ts
- src/module.ts
- src/pipes.ts
- src/services.ts
- src/utils.ts
It looks ugly having to write 
`resource.relationships.author.reference.resource.relationships.profile.resource.attributes.name`
This PR will create a method (and a Pipe) that will accept: `author.profile.name` and it will either get that actual field or the long path written above.
> Path resolver for denormalised resources

- karma.conf.js
- spec/selectors.spec.ts
- src/selectors.ts
When a StoreQuery has an empty `resultsId`, this should be caught
and an empty array should be returned.
Fixes #73
> Return an empty array for queries with no results

- spec/api.spec.ts
- spec/utils.spec.ts
- src/api.ts
- src/interfaces.ts
- src/selectors.ts
- src/services.ts
- src/utils.ts
- server url always read from configuration and not duplicated to allow reconfiguring or lazy configuring the url.
- some fields on StoreResource made optional to ease setting up new resources by ngrx-json-api consumers and then sending them to the store with the post action.
- removed unused imports
- added explicit return type for some selectors
- allow validation errors for POSTs to be written back to store by remembering the id in the action payload
> minor misc fixes

- src/selectors.ts
made use of proper OneQueryResult type instead of ManyQueryResult to return a single result
> minor (random) compile error fix

- spec/selectors.spec.ts
- spec/services.spec.ts
- src/selectors.ts
- src/services.ts
- src/utils.ts
- adapted selector/service accordingly
- should also be quite a bit faster as the number of involved observables (one per result) has been greatly reduced.
> move denormalization into selection process #121

- src/selectors.ts
- src/services.ts
- `getOneQueryResult$` is not used anywhere, it also had an error.
- `Options` cannot extend the specialised Options because the properties need to be set as required or optional in both interfaces.
- Small fix for type assertion.
- `denormaliseResource` needs to be public because it is used in the pipe.
> Fix build and remove getOneQueryResult$ selector

- src/reducers.ts
Previously, when trying to create or update a resource which is
already in the store (exactly as it is) the reducers responsible
will ignore the new data and just return the original state.
This has a side effect of ignoring to change `isUpdating` or
`isCreating` which is essential when using the library.
The status update is mandatory regardless if the data is already in
the store or not.
> Always change the operation status

- src/interfaces.ts
two interfaces have been added to facilitate generating Typescript interfaces from the backend model. The introduced generic interfaces will allow fully typesafe navigation of relationships.
A first backend project supporting this kind of code generation is www.crnk.io.
An example would look like:
````
export module Person{
export interface Relationships {
[key: string]: ResourceRelationship;
address?: TypedOneResourceRelationship<Address>;
}
export interface Attributes {
name?: string;
}
}
export interface Person extends MetaElement, StoreResource{
relationships?: Person.Relationships;
attributes?: Person.Attributes;
}
````
> interfaces to support code generators #173

- src/interfaces.ts
- src/utils.ts
introduced hasTemporaryId flag to mark a resource as having a temporary ID till the point a permanent one is assigned by a POST request.
> add support for server-generated ids #211

- src/effects.ts
This update removes calls to explicitly parse responses as json, i.e. `.map(res => res.json())`, because we’re now using the new `HttpClient` and it’s not necessary. This was causing issues such as #217.
Unfortunately the build is failing for me, so not quite sure how to proceed. @abdulhaq-e any thoughts?
> Remove explicit json parsing

- src/utils.ts
Prior to these changes, I was experiencing the following errors:
```shell
[22:57:30]  typescript: node_modules/ngrx-json-api/src/utils.ts, line: 57
Argument of type 'ResourceIdentifier | ResourceIdentifier[]' is not assignable to parameter of type
'ResourceIdentifier[]'. Type 'ResourceIdentifier' is not assignable to type 'ResourceIdentifier[]'. Property
'length' is missing in type 'ResourceIdentifier'.
L56:  let relatedRSs: Array<StoreResource> = getMultipleStoreResource(
L57:    data,
L58:    storeData
[22:57:30]  typescript: node_modules/ngrx-json-api/src/utils.ts, line: 590
Type 'Resource | (Resource | Resource[])[]' is not assignable to type 'Resource | Resource[]'. Type
'(Resource | Resource[])[]' is not assignable to type 'Resource | Resource[]'. Type '(Resource |
Resource[])[]' is …
```
> Fix typescript assignable datatype ambiguities

- package.json
- tsconfig-build.json
not sure what is going on with all the modules, but ES5 as default seems more reasonable currently. Angular CLI breaks otherwise.
> do make use of target=es5 in tsconfig #241

- package.json
- spec/actions.spec.ts
- spec/api.spec.ts
- spec/effects.spec.ts
- spec/pipes.spec.ts
- spec/reducers.spec.ts
- spec/selectors.spec.ts
- spec/services.spec.ts
- spec/testing.module.ts
- spec/utils.spec.ts
- src/actions.ts
- src/effects.ts
- src/index.ts
- src/interfaces.ts
- src/module.ts
- src/reducers.ts
- src/selectors.ts
- src/services.ts
- src/utils.ts
introduced new concept of zones to isolate multiple instances of ngrx-json-api:
- actions carry zoneId
- NgrxJsonApiService.getZone(...) allows access to zone-specific actions.
- NgrxJsonApiService continues to provide access to default zone.
- top-level layout in store changed with {zones:{default:{...}} data structure. Mostly hidden from consumers by providing updated selector functions.
- selector service deprecated in favor of pure functions. No need for a service.
- NGRX_JSON_API_DEFAULT_ZONE constant introduced.
- initialNgrxJsonApiZone constant introduced for empty zone.
> support multiple instances of store #244

- src/interfaces.ts
To avoid the error below on assigning `loading`.
```
error TS2322: Type 'Boolean' is not assignable to type 'boolean'.
'boolean' is a primitive, but 'Boolean' is a wrapper object. Prefer using 'boolean' when possible.
```
> Use boolean type

- spec/pipes.spec.ts
- spec/selectors.spec.ts
- spec/services.spec.ts
- src/index.ts
- src/pipes.ts
- src/selectors.ts
- src/services.ts
plural version of `jaSelectStoreResource`
it can be used as `{{person.relationships.blogs.data | jaSelectStoreResources as blogs}}` instead of using `*ngFor` and `jaSelectStoreResource` inside of it.
> jaSelectStoreResources pipe

- src/api.ts
- src/interfaces.ts
It is not defined the value of key of page in jsonapi.
http://jsonapi.org/format/#fetching-pagination
In our project, we are using `number` and `size` instead of `offset` and `limit`  as parmeters of pagination, so I'm stuck. Could you please help me?
> Accept page-based params (page[number] and page[size])

- src/api.ts
- src/interfaces.ts
Allows to send/receive cookies, authorization headers with cross-site request.
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials
> add requestWithCredentials option to NgrxJsonApiConfig

- spec/utils.spec.ts
- src/utils.ts
> fix: NgrxJsonApiZoneService applies pending changes in reverse order
